"""empty message

Revision ID: b8443dc5bfc5
Revises: 
Create Date: 2022-09-11 13:32:18.623625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8443dc5bfc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('video_link', sa.String(), nullable=True),
    sa.Column('gdrive_link', sa.String(), nullable=True),
    sa.Column('thumbnail_link', sa.String(), nullable=True),
    sa.Column('likes', sa.String(), nullable=True),
    sa.Column('total_comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_s')
    # ### end Alembic commands ###
